### ISSUE TITLE
BCH Transactions do not work

### ISSUE THREAD

**Issue by storm-breaker2** [thorswap/thorswap-finance-app#73]
No BCH transactions are currently supported.  This includes sending, swapping and liquidity provision. I believe this bug is predominately caused by bitcoincash: prefix to every BCH address.

**Comment by skyorion427** [comment]
fixed

**Comment by storm-breaker2** [comment]
Still does not work. Tested on testnet. 
![Uploading image.png…]()
